import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { api } from "../api";
import { requestConfirm } from "../hooks";
import { Button } from "../components";

// Per-user sample data (#281) — a new/invited user can fill an empty
// account with the example dataset to explore, then wipe it in one click.
// A full reload after either action is the simplest way to refresh every
// tab's data at once.
export function SampleDataSettings({
  onError,
}: {
  onError: (message: string | null) => void;
}) {
  const { t } = useTranslation();
  const [status, setStatus] = useState<{
    loaded: boolean;
    hasData: boolean;
  } | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    api
      .sampleDataStatus()
      .then(setStatus)
      .catch((e) => onError((e as Error).message));
  }, [onError]);

  if (!status) return null;
  // Nothing to offer once the account has real (non-sample) data.
  if (status.hasData && !status.loaded) return null;

  const load = () => {
    setBusy(true);
    api
      .loadSampleData()
      .then(() => window.location.reload())
      .catch((e) => {
        onError((e as Error).message);
        setBusy(false);
      });
  };
  const clear = async () => {
    if (!(await requestConfirm(t("sampleData.clearConfirm")))) return;
    setBusy(true);
    api
      .clearSampleData()
      .then(() => window.location.reload())
      .catch((e) => {
        onError((e as Error).message);
        setBusy(false);
      });
  };

  return (
    <div className="sample-data">
      <h3>{t("sampleData.title")}</h3>
      {status.loaded ? (
        <>
          <p className="muted small">{t("sampleData.loadedHint")}</p>
          <Button variant="secondary" disabled={busy} onClick={clear}>
            {t("sampleData.clear")}
          </Button>
        </>
      ) : (
        <>
          <p className="muted small">{t("sampleData.emptyHint")}</p>
          <Button variant="primary" disabled={busy} onClick={load}>
            {t("sampleData.load")}
          </Button>
        </>
      )}
    </div>
  );
}

// Data export / portability (#485) — moved into Settings → Data (it used to
// hide in the Insights stats drawer, leaving this tab blank for anyone with
// real data). Download everything as JSON, or a resource as CSV.
export function DataExport() {
  const { t } = useTranslation();
  const csvResources = ["applications", "companies", "contacts", "interactions"];
  return (
    <div className="data-export">
      <h3>{t("stats.exportData")}</h3>
      <p className="muted small">{t("settings.exportHint")}</p>
      <p className="export-links">
        <a href="/api/export" download>
          {t("stats.exportAllJson")}
        </a>
        {/* Translated, like everything else the user reads. These four
            printed the raw resource key — "applications (CSV)", lowercase
            and English in every locale — beside a properly localised
            "Everything (JSON)" on the same line. */}
        {csvResources.map((res) => (
          <a key={res} href={`/api/export/${res}.csv`} download>
            {t("stats.exportCsv", { resource: t(`export.${res}`) })}
          </a>
        ))}
      </p>
    </div>
  );
}

export function ResetDemoData() {
  const { t } = useTranslation();
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  const reset = async () => {
    // Confirmed, because "reset" understates it: the endpoint calls
    // wipeUserData, which deletes every user-scoped row across roughly
    // fifteen tables, and only then reseeds. Its two siblings — clearing
    // sample data, and deleting an account — both ask first; this one fired
    // on a single click.
    //
    // Not given the danger-zone treatment those get, deliberately. It acts
    // only on the demo account, it is admin-only, and the state it destroys
    // is regenerated by the same call. Reserving red for the irreversible
    // ones is what keeps red meaning something.
    if (!(await requestConfirm(t("account.resetDemoConfirm")))) return;
    setBusy(true);
    setMessage(null);
    try {
      const res = await fetch("/api/admin/reset-demo-data", { method: "POST" });
      setMessage(
        res.ok ? t("account.resetDemoSuccess") : t("account.resetDemoError"),
      );
    } catch {
      setMessage(t("account.resetDemoError"));
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="admin-invite">
      <h3>{t("account.resetDemo")}</h3>
      {/* What it does, before it is done. "Reset" reads like "restore
          defaults", and the delete half was invisible. */}
      <p className="muted small">{t("account.resetDemoHint")}</p>
      {message && <p className="admin-invite-success">{message}</p>}
      <Button variant="secondary" disabled={busy} onClick={reset}>
        {t("account.resetDemoSubmit")}
      </Button>
    </div>
  );
}
